services:
  - type: web
    name: flask-ml-app
    env: python
    buildCommand: ""
    startCommand: gunicorn run:app
    pythonVersion: 3.12.6
    envVars:
      - key: FLASK_ENV
        value: production
