services:
  - type: web
    name: flask-ml-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python nltk_download.py
    startCommand: gunicorn run:app
    pythonVersion: 3.10
    envVars:
      - key: FLASK_ENV
        value: production
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
